name = "Daman"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "43.218.77.16:443"
UUID = "1c1c25e2-4fb2-49c4-8e9c-fe5614150d6f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
